// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IGroth16Verifier
/// @notice Interface for the SnarkJS-generated Groth16 verifier contract.
/// @author Aditya Chotaliya [adityachotaliya.xyz]  
/// @dev The actual Groth16Verifier.sol is auto-generated by:
///      snarkjs zkey export solidityverifier task_final.zkey Groth16Verifier.sol
///      Its verifyProof signature matches this interface exactly.
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof.
    /// @param _pA  Proof element A (2 field elements)
    /// @param _pB  Proof element B (2x2 field elements)
    /// @param _pC  Proof element C (2 field elements)
    /// @param _pubSignals Public signals: [taskId, outputHash]
    /// @return True if the proof is valid for the given public signals.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[2] calldata _pubSignals
    ) external view returns (bool);
}
